octossh:
  image: joshuacox/octossh:${TAG}
  environment:
    KEY_URL: ${KEY_URL}
  ports:
  - "${SSH_PORT}:22"
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}
  external_links:
    - ${external_link}:extlink
