.catalog:
  name: "meanshop"
  version: "0.4.6"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "PORT"
        description: "Port to use for the MEANSHOP server"
        label: "MEANSHOP Port"
        required: true
        default: "3547"
        type: "int"
      - variable: replset_name
        description: "Name of the MongoDB replicaSet"
        label: "ReplicaSet Name"
        type: "string"
        required: true
        default: "rs0"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'meanshop=true'
        required: false
        default: "meanshop=true"
        type: "string"

meanshop-nginx:
  scale: 1
  retain_ip: true

meanshop-node:
  scale: 1
  retain_ip: true

meango:
  scale: 1
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
