version: '2'
catalog:
  name: "captain-hook"
  version: "0.0.1"
  description: "Captain Hook generic webhook xmitter"
  uuid: captain-hook-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "SERVER_PORT"
        description: "Server port to use for the captain hook container"
        label: "Port"
        required: true
        default: "3000"
        type: "string"
      - variable: "TOKEN"
        description: "Token to use for captain hook"
        label: "Token"
        required: true
        default: "abc123"
        type: "string"
      - variable: "ROUTE"
        description: "Route to use for captain hook"
        label: "Route"
        required: true
        default: "/api"
        type: "string"
      - variable: "CAPTAIN_HOOK_DOMAIN"
        description: "Domain to use for the Thalhalla store server"
        label: "CAPTAIN_HOOK Domain"
        required: true
        default: ""
        type: "string"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'captainhook=true'
        required: false
        default: "captainhook=true"
        type: "string"
services:
  captainhook:
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
