version: '2'
services:
  helloworld-nginx:
    image: nginx:stable-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.alias: ${HELLOWORLD_HOST}
      traefik.domain: ${HELLOWORLD_DOMAIN}
      traefik.acme: true
      traefik.port: 80
    environment:
      NGINX_HOST: ${HELLOWORLD_HOST}.${HELLOWORLD_DOMAIN}
      NGINX_PORT: 80
    command:
      - echo
      - 'hello world'
      - '>'
      -  '/usr/share/nginx/html/index.html'
      -  ;
      -  nginx
      -  -g
      -  'daemon'
