version: '2'
catalog:
  name: "meteordemo"
  version: 1.4.0-rancher3
  description: "E-commerce powered by meteor"
  uuid: meteor-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "METEOR_HOST"
        description: "Hostname to use for the meteor server"
        label: "meteor Hostname"
        required: true
        default: "meteor"
        type: "string"
      - variable: "METEOR_DOMAIN"
        description: "Domain to use for the meteor server"
        label: "meteor Domain"
        required: true
        default: "local"
        type: "string"
      - variable: "METEOR_IMAGE"
        default: "meteorcommerce/meteor:v1.4.1"
        description: "Image to use for the meteor server"
        label: "meteor image"
        required: true
        type: "string"
      - variable: host_label
        label: "Host Label to meteor Tags"
        description: |
          Host label to use as meteor 'value' tag.
          Example: 'meteor=true'
        required: false
        default: "private=true"
        type: "string"
      - variable: METEOR_USER
        label: "meteor User"
        required: true
        default: ""
        type: "string"
      - variable: METEOR_AUTH
        label: "meteor Auth"
        required: true
        default: ""
        type: "password"
      - variable: METEOR_EMAIL
        label: "meteor Email"
        required: true
        default: "test@local"
        type: "string"
      - variable: METEOR_LOG_LEVL
        label: "meteor log level"
        required: true
        default: "INFO"
        type: enum
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL
      - variable: MAIL_URL
        label: "meteor mail url"
        description: |
          meteor supports sending mail over SMTP;
          the MAIL_URL environment variable should be of the form
          smtp://USERNAME:PASSWORD@HOST:PORT
        required: true
        default: "smtp://user:pass@example.com:587"
        type: "string"
      - variable: "mongo_link"
        description: |
          MongoDB external service link
          cluster.
        label: "External stack/service"
        default: ""
        required: false
        type: "service"
      - variable: "MONGO_DB"
        default: "meteor"
        description: "The mongodb name to associate with this server."
        label: "mongo_db"
        required: true
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server"
        label: "VOLUME Driver"
        required: true
        default: "rancher-nfs"
        type: enum
        options:
          - local
          - rancher-nfs
          - rancher-efs
          - rancher-ebs


services:
  meteor:
    scale: 1
    retain_ip: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 3000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / # HTTP/1.0
