.catalog:
  name: "meanshop"
  version: "0.5.2"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "MEANGO_HOST"
        description: "Mongo Host to use for the MEANSHOP server"
        label: "Mongo Host"
        required: true
        default: "mymongo_host"
        type: "string"
      - variable: "MEANGO_DEBUG"
        description: "include debug data in stdout"
        label: "debug"
        required: false
        type: "string"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'meanshop=true'
        required: false
        default: "meanshop=true"
        type: "string"

meanshop-nginx:
  scale: 1
  retain_ip: true
  health_check:
    # Which port to perform the check against
    port: 80
    # For TCP, request_line needs to be '' or not shown
    # TCP Example:
    # request_line: ''
    # request_line: GET / HTTP/1.0
    request_line: GET / HTTP/1.0
    # Interval is measured in milliseconds
    interval: 30000
    initializing_timeout: 360000
    unhealthy_threshold: 9
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: none
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 9000

meanshop-node:
  scale: 1
  retain_ip: true
