.catalog:
  name: "moviemasher"
  version: "0.1.19"
  description: "Library service powered by Moviemasher"
  uuid: moviemasher-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MOVIEMASHER_HOST"
        description: "Hostname to use for the MOVIEMASHER server"
        label: "MOVIEMASHER Hostname"
        required: true
        default: "moviemasher"
        type: "string"
      - variable: "MOVIEMASHER_DOMAIN"
        description: "Domain to use for the MOVIEMASHER server"
        label: "MOVIEMASHER Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "PORT"
        type: "int"
        label: "Port Number"
        description: "Which port should MovieMasher listen on?"
        default: 11080
        required: true

moviemasher:
  scale: 1
  retain_ip: true
moviemasherrb:
  scale: 1
