.catalog:
  name: "meanshop"
  version: "0.4.0"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "DB_VOLUME_NAME"
        description: "The VOLUME name to associate with the DB of this server"
        label: "DB VOLUME Name"
        required: true
        default: "MEANSHOP_DB"
        type: "string"
      - variable: replset_name
        description: "Name of the MongoDB replicaSet"
        label: "ReplicaSet Name"
        type: "string"
        required: true
        default: "rs0"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'meanshop=true'
        required: false
        default: "meanshop=true"
        type: "string"

meanshop-nginx:
  scale: 1
  retain_ip: true
  health_check:
    # Which port to perform the check against
    port: 80
    # For TCP, request_line needs to be '' or not shown
    # TCP Example:
    # request_line: ''
    # request_line: GET / HTTP/1.0
    request_line: ''
    # Interval is measured in milliseconds
    interval: 30000
    initializing_timeout: 360000
    unhealthy_threshold: 9
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: none
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 9000

meanshop-node:
  scale: 1
  retain_ip: true

meango-base:
  scale: 1
  retain_ip: true

meango-cluster:
  scale: 1
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
