version: '2'
catalog:
  name: "helloworld-traefik"
  version: "0.1.1"
  description: "Traefik Hello World"
  uuid: helloworldtraefik-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "HELLOWORLD_HOST"
        description: "Hostname to use for the HELLOWORLD server"
        label: "HELLOWORLD Hostname"
        required: true
        default: "helloworld"
        type: "string"
      - variable: "HELLOWORLD_DOMAIN"
        description: "Domain to use for the HELLOWORLD server"
        label: "HELLOWORLD Domain"
        required: true
        default: "example.com"
        type: "string"
services:
  helloworld-nginx:
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
