version: '2'
catalog:
  name: "meanshop"
  version: "0.5.6"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "MEANGO_HOST"
        description: "Mongo Host to use for the MEANSHOP server"
        label: "Mongo Host"
        required: true
        default: "mymongo_host"
        type: "string"
      - variable: "MEANGO_DEBUG"
        description: "include debug data in stdout"
        label: "debug"
        required: false
        type: "string"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'meanshop=true'
        required: false
        default: "meanshop=true"
        type: "string"
services:
  meanshop-nginx:
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
  meanshop-node:
    scale: 1
