version: '2'
services:
  meanshopdb:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - meanshop-data
    labels:
      io.rancher.sidekicks: meanshopdb,meanshop-data
      io.rancher.container.pull_image: always
  meanshopweb:
    image: thalhalla/meanshop
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: meanshopdb,meanshop-data
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.alias: ${MEANSHOP_HOST}
      traefik.domain: ${MEANSHOP_DOMAIN}
      traefik.acme: true
      traefik.port: 7000
    command: npm start
      - "7000:7000"
    volumes_from:
      - meanshop-data
    environment:
      PORT: 7000
      MONGODB_DB_URL: "mongodb://meanshopdb/meanshop"
  meanshop-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.container.pull_image: always
    volume_driver: ${VOLUME_DRIVER}
    volumes:
      - ${VOLUME_NAME}:/meanshop
      - ${DB_VOLUME_NAME}:/data/db
