.catalog:
  name: "meanshop"
  version: "0.1.4"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "MEANSHOP"
        type: "string"
      - variable: "DB_VOLUME_NAME"
        description: "The VOLUME name to associate with the DB of this server"
        label: "DB VOLUME Name"
        required: true
        default: "MEANSHOP_DB"
        type: "string"

meanshop:
  scale: 1
  retain_ip: true
  health_check:
    port: 7000
    interval: 30000
    unhealthy_threshold: 6
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 4
