.catalog:
  name: Jenkins
  version: 2.32-ohmyjenkins-074
  description: |
    Jenkins CI management server.
  questions:
  - variable: "JENKINS_HOST"
    description: "Hostname to use for the JENKINS server (for Traefik labels)"
    label: "JENKINS Hostname"
    required: true
    default: "jenkins"
    type: "string"
  - variable: "JENKINS_DOMAIN"
    description: "Domain to use for the JENKINS server (for Traefik labels)"
    label: "JENKINS Domain"
    required: true
    default: "example.com"
    type: "string"
  - variable: "VOLUME_WORK"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "JENKINS"
    type: "string"
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: |
      List of plugins in the format <plugin_name>[:<version>]
      one entry per line.
    default: |
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
    label: "VOLUME Driver"
    required: true
    default: "convoy-nfs"
    type: "string"
jenkins-primary:
  metadata:
    plugins: |
      ${plugins}
  health_check:
    port: 8080
    # For TCP, request_line needs to be '' or not shown
    # TCP Example:
    # request_line: ''
    # request_line: GET / HTTP/1.0
    request_line: ''
    # Interval is measured in milliseconds
    interval: 30000
    unhealthy_threshold: 9
    strategy: none
    response_timeout: 10000
    healthy_threshold: 2
