version: '2'
catalog:
  name: "Kibana"
  version: "5.5.0-rancher2"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"

services:
  kibana:
    health_check:
      port: 5601
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
