name: MediaGoblin
description: |
  MediaGoblin is a free software media publishing platform that anyone can run. You can think of it as a decentralized alternative to Flickr, YouTube, SoundCloud, etc.
version: 0.0.4
category: Media
