version: '2'

services:

  wordpress:
    image: ohmydocker/docker-wordpress-wp-cli:adjustingalternatives
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.sidekicks: mysql,wordpress-datavolume
      io.rancher.container.pull_image: always
    environment:
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_SITE_URL=${WORDPRESS_SITE_URL}
        - WORDPRESS_PORT=${WORDPRESS_PORT}
        - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
        - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
        - WORDPRESS_TITLE=${WORDPRESS_TITLE}
        - WORDPRESS_TAGLINE=${WORDPRESS_TAGLINE}
    ports:
      - ${WORDPRESS_PORT}:80
    volumes_from:
      - wordpress-datavolume
    restart: always

  mysql:
    restart: always
    image: mariadb
    volumes_from:
    - wordpress-datavolume
    labels:
      io.rancher.sidekicks: wordpress-datavolume
      io.rancher.scheduler.affinity:host_label: ${host_label}
    environment:
    - MYSQL_USER=${WORDPRESS_DB_USER}
    - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}
    - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
    - SKIP_NAME_RESOLVE=Yes

  wordpress-datavolume:
    image: "busybox"
    volume_driver: ${VOLUME_DRIVER}
    volumes:
      - ${VOLUME_NAME}:/var/www/html
      - ${DB_VOLUME_NAME}:/var/lib/mysql
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: ${host_label}
    entrypoint: ["/bin/true"]
