.catalog:
  name: "Meanshop"
  version: "0.1.1"
  description: "Library service powered by Meanshop"
  uuid: meanshop-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: ""
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "MEANSHOP"
        type: "string"
      - variable: "DB_VOLUME_NAME"
        description: "The VOLUME name to associate with the DB of this server"
        label: "DB VOLUME Name"
        required: true
        default: "MEANSHOP_DB"
        type: "string"

meanshop:
